/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as AuthenticatedWidgetsIndexRouteImport } from './routes/_authenticated/widgets/index'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects/index'
import { Route as AuthenticatedPostsIndexRouteImport } from './routes/_authenticated/posts/index'
import { Route as AuthenticatedMomentsIndexRouteImport } from './routes/_authenticated/moments/index'
import { Route as AuthenticatedFriendsIndexRouteImport } from './routes/_authenticated/friends/index'
import { Route as AuthenticatedProjectsNewRouteImport } from './routes/_authenticated/projects/new'
import { Route as AuthenticatedPostsNewRouteImport } from './routes/_authenticated/posts/new'
import { Route as AuthenticatedPostsCategoriesRouteImport } from './routes/_authenticated/posts/categories'
import { Route as AuthenticatedMomentsNewRouteImport } from './routes/_authenticated/moments/new'
import { Route as AuthenticatedFriendsNewRouteImport } from './routes/_authenticated/friends/new'
import { Route as AuthenticatedFriendsCategoriesRouteImport } from './routes/_authenticated/friends/categories'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedProjectsProjectIdEditRouteImport } from './routes/_authenticated/projects/$projectId/edit'
import { Route as AuthenticatedPostsPostIdEditRouteImport } from './routes/_authenticated/posts/$postId/edit'
import { Route as AuthenticatedMomentsPostIdEditRouteImport } from './routes/_authenticated/moments/$postId/edit'
import { Route as AuthenticatedFriendsFriendIdEditRouteImport } from './routes/_authenticated/friends/$friendId/edit'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWidgetsIndexRoute =
  AuthenticatedWidgetsIndexRouteImport.update({
    id: '/widgets/',
    path: '/widgets/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPostsIndexRoute = AuthenticatedPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMomentsIndexRoute =
  AuthenticatedMomentsIndexRouteImport.update({
    id: '/moments/',
    path: '/moments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFriendsIndexRoute =
  AuthenticatedFriendsIndexRouteImport.update({
    id: '/friends/',
    path: '/friends/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsNewRoute =
  AuthenticatedProjectsNewRouteImport.update({
    id: '/projects/new',
    path: '/projects/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPostsNewRoute = AuthenticatedPostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPostsCategoriesRoute =
  AuthenticatedPostsCategoriesRouteImport.update({
    id: '/posts/categories',
    path: '/posts/categories',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMomentsNewRoute = AuthenticatedMomentsNewRouteImport.update({
  id: '/moments/new',
  path: '/moments/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFriendsNewRoute = AuthenticatedFriendsNewRouteImport.update({
  id: '/friends/new',
  path: '/friends/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFriendsCategoriesRoute =
  AuthenticatedFriendsCategoriesRouteImport.update({
    id: '/friends/categories',
    path: '/friends/categories',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdEditRoute =
  AuthenticatedProjectsProjectIdEditRouteImport.update({
    id: '/projects/$projectId/edit',
    path: '/projects/$projectId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPostsPostIdEditRoute =
  AuthenticatedPostsPostIdEditRouteImport.update({
    id: '/posts/$postId/edit',
    path: '/posts/$postId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMomentsPostIdEditRoute =
  AuthenticatedMomentsPostIdEditRouteImport.update({
    id: '/moments/$postId/edit',
    path: '/moments/$postId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFriendsFriendIdEditRoute =
  AuthenticatedFriendsFriendIdEditRouteImport.update({
    id: '/friends/$friendId/edit',
    path: '/friends/$friendId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/friends/categories': typeof AuthenticatedFriendsCategoriesRoute
  '/friends/new': typeof AuthenticatedFriendsNewRoute
  '/moments/new': typeof AuthenticatedMomentsNewRoute
  '/posts/categories': typeof AuthenticatedPostsCategoriesRoute
  '/posts/new': typeof AuthenticatedPostsNewRoute
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/friends/': typeof AuthenticatedFriendsIndexRoute
  '/moments/': typeof AuthenticatedMomentsIndexRoute
  '/posts/': typeof AuthenticatedPostsIndexRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/widgets/': typeof AuthenticatedWidgetsIndexRoute
  '/friends/$friendId/edit': typeof AuthenticatedFriendsFriendIdEditRoute
  '/moments/$postId/edit': typeof AuthenticatedMomentsPostIdEditRoute
  '/posts/$postId/edit': typeof AuthenticatedPostsPostIdEditRoute
  '/projects/$projectId/edit': typeof AuthenticatedProjectsProjectIdEditRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/friends/categories': typeof AuthenticatedFriendsCategoriesRoute
  '/friends/new': typeof AuthenticatedFriendsNewRoute
  '/moments/new': typeof AuthenticatedMomentsNewRoute
  '/posts/categories': typeof AuthenticatedPostsCategoriesRoute
  '/posts/new': typeof AuthenticatedPostsNewRoute
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/friends': typeof AuthenticatedFriendsIndexRoute
  '/moments': typeof AuthenticatedMomentsIndexRoute
  '/posts': typeof AuthenticatedPostsIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/widgets': typeof AuthenticatedWidgetsIndexRoute
  '/friends/$friendId/edit': typeof AuthenticatedFriendsFriendIdEditRoute
  '/moments/$postId/edit': typeof AuthenticatedMomentsPostIdEditRoute
  '/posts/$postId/edit': typeof AuthenticatedPostsPostIdEditRoute
  '/projects/$projectId/edit': typeof AuthenticatedProjectsProjectIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/friends/categories': typeof AuthenticatedFriendsCategoriesRoute
  '/_authenticated/friends/new': typeof AuthenticatedFriendsNewRoute
  '/_authenticated/moments/new': typeof AuthenticatedMomentsNewRoute
  '/_authenticated/posts/categories': typeof AuthenticatedPostsCategoriesRoute
  '/_authenticated/posts/new': typeof AuthenticatedPostsNewRoute
  '/_authenticated/projects/new': typeof AuthenticatedProjectsNewRoute
  '/_authenticated/friends/': typeof AuthenticatedFriendsIndexRoute
  '/_authenticated/moments/': typeof AuthenticatedMomentsIndexRoute
  '/_authenticated/posts/': typeof AuthenticatedPostsIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/widgets/': typeof AuthenticatedWidgetsIndexRoute
  '/_authenticated/friends/$friendId/edit': typeof AuthenticatedFriendsFriendIdEditRoute
  '/_authenticated/moments/$postId/edit': typeof AuthenticatedMomentsPostIdEditRoute
  '/_authenticated/posts/$postId/edit': typeof AuthenticatedPostsPostIdEditRoute
  '/_authenticated/projects/$projectId/edit': typeof AuthenticatedProjectsProjectIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/errors/$error'
    | '/friends/categories'
    | '/friends/new'
    | '/moments/new'
    | '/posts/categories'
    | '/posts/new'
    | '/projects/new'
    | '/friends/'
    | '/moments/'
    | '/posts/'
    | '/projects/'
    | '/widgets/'
    | '/friends/$friendId/edit'
    | '/moments/$postId/edit'
    | '/posts/$postId/edit'
    | '/projects/$projectId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/errors/$error'
    | '/friends/categories'
    | '/friends/new'
    | '/moments/new'
    | '/posts/categories'
    | '/posts/new'
    | '/projects/new'
    | '/friends'
    | '/moments'
    | '/posts'
    | '/projects'
    | '/widgets'
    | '/friends/$friendId/edit'
    | '/moments/$postId/edit'
    | '/posts/$postId/edit'
    | '/projects/$projectId/edit'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/errors/$error'
    | '/_authenticated/friends/categories'
    | '/_authenticated/friends/new'
    | '/_authenticated/moments/new'
    | '/_authenticated/posts/categories'
    | '/_authenticated/posts/new'
    | '/_authenticated/projects/new'
    | '/_authenticated/friends/'
    | '/_authenticated/moments/'
    | '/_authenticated/posts/'
    | '/_authenticated/projects/'
    | '/_authenticated/widgets/'
    | '/_authenticated/friends/$friendId/edit'
    | '/_authenticated/moments/$postId/edit'
    | '/_authenticated/posts/$postId/edit'
    | '/_authenticated/projects/$projectId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/widgets/': {
      id: '/_authenticated/widgets/'
      path: '/widgets'
      fullPath: '/widgets/'
      preLoaderRoute: typeof AuthenticatedWidgetsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/posts/': {
      id: '/_authenticated/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof AuthenticatedPostsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/moments/': {
      id: '/_authenticated/moments/'
      path: '/moments'
      fullPath: '/moments/'
      preLoaderRoute: typeof AuthenticatedMomentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/friends/': {
      id: '/_authenticated/friends/'
      path: '/friends'
      fullPath: '/friends/'
      preLoaderRoute: typeof AuthenticatedFriendsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/new': {
      id: '/_authenticated/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AuthenticatedProjectsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/posts/new': {
      id: '/_authenticated/posts/new'
      path: '/posts/new'
      fullPath: '/posts/new'
      preLoaderRoute: typeof AuthenticatedPostsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/posts/categories': {
      id: '/_authenticated/posts/categories'
      path: '/posts/categories'
      fullPath: '/posts/categories'
      preLoaderRoute: typeof AuthenticatedPostsCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/moments/new': {
      id: '/_authenticated/moments/new'
      path: '/moments/new'
      fullPath: '/moments/new'
      preLoaderRoute: typeof AuthenticatedMomentsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/friends/new': {
      id: '/_authenticated/friends/new'
      path: '/friends/new'
      fullPath: '/friends/new'
      preLoaderRoute: typeof AuthenticatedFriendsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/friends/categories': {
      id: '/_authenticated/friends/categories'
      path: '/friends/categories'
      fullPath: '/friends/categories'
      preLoaderRoute: typeof AuthenticatedFriendsCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/edit': {
      id: '/_authenticated/projects/$projectId/edit'
      path: '/projects/$projectId/edit'
      fullPath: '/projects/$projectId/edit'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/posts/$postId/edit': {
      id: '/_authenticated/posts/$postId/edit'
      path: '/posts/$postId/edit'
      fullPath: '/posts/$postId/edit'
      preLoaderRoute: typeof AuthenticatedPostsPostIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/moments/$postId/edit': {
      id: '/_authenticated/moments/$postId/edit'
      path: '/moments/$postId/edit'
      fullPath: '/moments/$postId/edit'
      preLoaderRoute: typeof AuthenticatedMomentsPostIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/friends/$friendId/edit': {
      id: '/_authenticated/friends/$friendId/edit'
      path: '/friends/$friendId/edit'
      fullPath: '/friends/$friendId/edit'
      preLoaderRoute: typeof AuthenticatedFriendsFriendIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedFriendsCategoriesRoute: typeof AuthenticatedFriendsCategoriesRoute
  AuthenticatedFriendsNewRoute: typeof AuthenticatedFriendsNewRoute
  AuthenticatedMomentsNewRoute: typeof AuthenticatedMomentsNewRoute
  AuthenticatedPostsCategoriesRoute: typeof AuthenticatedPostsCategoriesRoute
  AuthenticatedPostsNewRoute: typeof AuthenticatedPostsNewRoute
  AuthenticatedProjectsNewRoute: typeof AuthenticatedProjectsNewRoute
  AuthenticatedFriendsIndexRoute: typeof AuthenticatedFriendsIndexRoute
  AuthenticatedMomentsIndexRoute: typeof AuthenticatedMomentsIndexRoute
  AuthenticatedPostsIndexRoute: typeof AuthenticatedPostsIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedWidgetsIndexRoute: typeof AuthenticatedWidgetsIndexRoute
  AuthenticatedFriendsFriendIdEditRoute: typeof AuthenticatedFriendsFriendIdEditRoute
  AuthenticatedMomentsPostIdEditRoute: typeof AuthenticatedMomentsPostIdEditRoute
  AuthenticatedPostsPostIdEditRoute: typeof AuthenticatedPostsPostIdEditRoute
  AuthenticatedProjectsProjectIdEditRoute: typeof AuthenticatedProjectsProjectIdEditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedFriendsCategoriesRoute: AuthenticatedFriendsCategoriesRoute,
  AuthenticatedFriendsNewRoute: AuthenticatedFriendsNewRoute,
  AuthenticatedMomentsNewRoute: AuthenticatedMomentsNewRoute,
  AuthenticatedPostsCategoriesRoute: AuthenticatedPostsCategoriesRoute,
  AuthenticatedPostsNewRoute: AuthenticatedPostsNewRoute,
  AuthenticatedProjectsNewRoute: AuthenticatedProjectsNewRoute,
  AuthenticatedFriendsIndexRoute: AuthenticatedFriendsIndexRoute,
  AuthenticatedMomentsIndexRoute: AuthenticatedMomentsIndexRoute,
  AuthenticatedPostsIndexRoute: AuthenticatedPostsIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedWidgetsIndexRoute: AuthenticatedWidgetsIndexRoute,
  AuthenticatedFriendsFriendIdEditRoute: AuthenticatedFriendsFriendIdEditRoute,
  AuthenticatedMomentsPostIdEditRoute: AuthenticatedMomentsPostIdEditRoute,
  AuthenticatedPostsPostIdEditRoute: AuthenticatedPostsPostIdEditRoute,
  AuthenticatedProjectsProjectIdEditRoute:
    AuthenticatedProjectsProjectIdEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
